# """
#model_config.yaml - File cấu hình mô hình
# """

# Cấu hình dữ liệu
data:
  train_csv: 'dataset/labels.csv'
  img_dir: 'dataset/images/'
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  batch_size: 32
  num_workers: 4
  image_size: [32, 140]  # [height, width]
  max_length: 10  # Độ dài tối đa chuỗi ký tự
  chars: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-'  # Các ký tự cần nhận dạng

# Cấu hình tiền xử lý và tăng cường dữ liệu
preprocessing:
  normalize_mean: [0.5]
  normalize_std: [0.5]
  use_clahe: true
  clip_limit: 2.0
  tile_grid_size: [8, 8]
  adaptive_threshold: true

augmentation:
  enabled: true
  rotation_range: 5  # Góc xoay tối đa (độ)
  brightness_range: [0.8, 1.2]
  contrast_range: [0.8, 1.2]
  noise_probability: 0.2
  blur_probability: 0.1
  shadow_probability: 0.1

# Cấu hình mô hình
model:
  backbone: 'efficientnet_b0'  # vgg19, resnet18, mobilenet_v3_small, efficientnet_b0
  backbone_pretrained: true
  use_stn: true
  rnn_hidden_size: 256
  rnn_num_layers: 2
  rnn_bidirectional: true
  rnn_dropout: 0.2
  rnn_type: 'gru'  # gru, lstm
  attention_type: 'multi_head'  # additive, multi_head
  attention_heads: 8
  decoder_type: 'rnn'  # rnn, transformer
  embedding_dim: 256
  transformer_nhead: 8
  transformer_dim_feedforward: 2048
  transformer_dropout: 0.1
  use_language_model: true

# Cấu hình huấn luyện
training:
  epochs: 100
  optimizer: 'adam'  # adam, sgd, adamw
  learning_rate: 0.001
  weight_decay: 1e-5
  lr_scheduler: 'cosine'  # step, cosine, reduce_on_plateau
  lr_step_size: 20
  lr_gamma: 0.1
  early_stopping_patience: 10
  teacher_forcing_ratio: 0.5
  clip_gradient: 5.0
  mixed_precision: false

# Cấu hình loss
loss:
  type: 'combined'  # cross_entropy, ctc, focal, combined
  label_smoothing: 0.1
  focal_alpha: 0.25
  focal_gamma: 2.0
  cross_entropy_weight: 1.0
  ctc_weight: 0.5
  hard_mining: true
  hard_mining_ratio: 0.2

# Cấu hình hậu xử lý
postprocessing:
  use_beam_search: true
  beam_width: 5
  use_lexicon: true
  apply_license_plate_rules: true
  province_codes: "11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,40,41,42,43,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,88,89,90,92,93,94,95,97,98,99"
  serie_codes: "A,B,C,D,E,F,G,H,K,L,M,N,P,S,T,U,V,X,Y,Z"

# Cấu hình đánh giá
evaluation:
  metrics: ['accuracy', 'edit_distance', 'character_accuracy']
  confusion_matrix: true
  log_incorrect_predictions: true

# Cấu hình lưu trữ
checkpoint:
  save_dir: 'experiments/'
  save_best_only: true
  save_frequency: 5